### ISSUE TITLE
用一键脚本出错

### ISSUE THREAD

**Issue by zhaoqishan** [yuzd/AntDeploy#18]

**Comment by peiwen-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
最近在忙有事电联！

**Comment by yuzd** [comment]
服务器被回收了
可以参考https://www.cnblogs.com/yudongdong/p/14017569.html
进行手动部署

**Comment by yuzd** [comment]
curl https://files-cdn.cnblogs.com/files/yudongdong/install_antdeploy_agent.sh|sudo sh
@zhaoqishan
