### ISSUE TITLE
项目部署时，服务器是否可以多选。

### ISSUE THREAD

**Issue by ywj6792341** [yuzd/AntDeploy#2]
我的想法是 直接在 setting 定义好服务器的 部署类型(iis/docker/service)

如果是 .net framework,，则可以选择勾选多个 IIS服务器同时部署。
如果是 .net core，则可以先择勾选多个 Docker服务器、IIS服务器和Windows Service 服务器进行同时部署。。

这样的话可能会对集群部署的项目友好一些。不知道作者有兴趣不？

**Comment by yuzd** [comment]
这个暂时不考虑了。目前可以在环境下添加多台机器实现集群部署。。你这个方案可以考虑自己基于代码修改实现。
