### ISSUE TITLE
.net core2.0可以修改部署模式吗？独立部署

### ISSUE THREAD

**Issue by 17607103052** [yuzd/AntDeploy#3]

**Comment by yuzd** [comment]
1. 如果是发布到iis的话，独立部署没有必要，因为你想要发布到iis必须得在服务器装Hosting。装了Hosting那必然是装了dotnet runtime
2. 如果是发布windows服务 默认netcore就是独立部署的
3. 如果是Docker的话基本都是使用带有dotnet runtime作为base image。所以也不需要独立部署。

综上 我认为没有不要加一个修改部署模式的功能。
若有其他意见可以指出

**Comment by yuzd** [comment]
![image](https://user-images.githubusercontent.com/16083659/55332681-75ea6a00-54c8-11e9-95da-7c5fde87a956.png)

@17607103052 已支持了 请更新
