### ISSUE TITLE
大牛你好，麻烦把jib.exe上传一下，应该.gitignore过滤掉了

### ISSUE THREAD

**Issue by peijiehuang** [yuzd/AntDeploy#30]
RT，插件两个项目编译不成功

另外麻烦大牛加我一下，我加你群了，没响应

**Comment by peijiehuang** [comment]
另外想问一下大牛，jib.exe是干嘛用的，搜了一圈，还是一脸懵逼

**Comment by yuzd** [comment]
可以下载一下vsix插件 zip解压后 有这个文件
jib.exe是用来本地打包镜像（不依赖linux环境和docker环境）
参考了谷歌开源的jib项目用csharp实现的

**Comment by peijiehuang** [comment]
> 可以下载一下vsix插件 zip解压后 有这个文件 jib.exe是用来本地打包镜像（不依赖linux环境和docker环境） 参考了谷歌开源的jib项目用csharp实现的

多谢分享大牛，处理好了jib.exe，然而git2-106a5f2.dll文件又不存在

最后搜索发现是LibGit2Sharp的dll，唯有在AntDeployWinform手动复制到插件目录

项目完美生成成功

**Comment by peijiehuang** [comment]
解决方案，直接选中项目AntDeployWinform，右键属性-生成事件-生成后事件命令行

xCopy  "$(TargetDir)lib\win32"  "$(SolutionDir)AntDeploy2019\AntDeployVsix\lib\win32\"  /e
xCopy  "$(TargetDir)lib\win32"  "$(SolutionDir)AntDeploy2022\AntDeployV2\lib\win32\"  /e

**Comment by yuzd** [comment]
我一直没搞
你改了帮忙提交下

**Comment by peijiehuang** [comment]
已提交代码，不知道是不是这样，第一次提交
