### ISSUE TITLE
问一下，WindowsServiceTool.exe 有源码么

### ISSUE THREAD

**Issue by w8w8w8** [yuzd/AntDeploy#36]
我想要WindowsServiceTool.exe这个小程序的源码

**Comment by peiwen-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
最近在忙有事电联！

**Comment by yuzd** [comment]
有的 在群里面

![image](https://user-images.githubusercontent.com/16083659/200163215-968ca6b4-078a-420b-acd1-b8bb9c359dd2.png)
