### ISSUE TITLE
FireUrl是什么意思呀

### ISSUE THREAD

**Issue by DUWENINK** [yuzd/AntDeploy#39]

**Comment by peiwen-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
最近在忙有事电联！

**Comment by yuzd** [comment]
就是部署完成后会进行对这个fireUrl的请求
如果返回的statuscode在200~400区间就认为 部署是成功的
一般这个叫点火

**Comment by DUWENINK** [comment]
谢谢你的回答,可否支持一个webhook 就是部署完毕可以请求一下这个地址然后可以进行后续操作

**Comment by yuzd** [comment]
你说的这个我理解就是这个fireurl

**Comment by yuzd** [comment]
你可以在这个fireurl填写webhook的地址
