### ISSUE TITLE
发布到docker之后日志挂载不出来

### ISSUE THREAD

**Issue by liwenhai0745** [yuzd/AntDeploy#4]
是我哪里配置错了吗
![image](https://user-images.githubusercontent.com/32086111/62747722-4821bd00-ba88-11e9-8c36-4fcd5a162736.png)

进容器里看日志被拒绝
![image](https://user-images.githubusercontent.com/32086111/62747741-5a036000-ba88-11e9-8e87-973957e41226.png)

宿主里也没有日志文件
![image](https://user-images.githubusercontent.com/32086111/62747781-8b7c2b80-ba88-11e9-9251-6581b2359457.png)

**Comment by yuzd** [comment]
你进容器里面看有没有 publish/logs
这个文件夹呢

**Comment by liwenhai0745** [comment]
这个图就是看日志的啊，应用启动的时候会创建Logs这个文件夹的，并向里面写日志文件。看这个图，logs文件夹是被创建出来了，但是有权限问题，我没法看到里面的日志文件，【Permission denied】。 如果在发布的时候不挂载日志，那么就可以进入到容器里看到这个日志。 您可以做个demo挂载日志到宿主试试
![image](https://user-images.githubusercontent.com/32086111/62750668-840e4f80-ba93-11e9-9132-f82306c7408c.png)

**Comment by yuzd** [comment]
![image](https://images4.c-ctrip.com/target/zb0w170000011dnl724D0.png)
![image](https://images4.c-ctrip.com/target/zb0d170000011653lB09D.png)

并没有再现你这个权限问题。
而且你这个提示挺奇怪的，你能进容器之后 先打印下publish 目录下 有没有 logs 文件夹吗

**Comment by liwenhai0745** [comment]
您好，早上我在家里又重新搭建了一个项目试了一下，结果成功挂载日志到宿主，您的软件没问题。这个工具非常好用，大大提升了部署的效率，对你表示感谢。祝你生活愉快。

**Comment by yuzd** [comment]
谢谢支持

**Comment by liwenhai0745** [comment]
我到公司又试了一下，在容器里Logs文件夹是创建出来了，但是ls的时候就没有权限



百度后的结果，希望工具在运行docker时给加上  --privileged=true 



------------------ 原始邮件 ------------------
发件人: "nainaigu"<notifications@github.com>;
发送时间: 2019年8月10日(星期六) 中午12:53
收件人: "yuzd/AntDeploy"<AntDeploy@noreply.github.com>;
抄送: "624302265@qq.com "<624302265@QQ.com>;"Author"<author@noreply.github.com>;
主题: Re: [yuzd/AntDeploy] 发布到docker之后日志挂载不出来 (#4)




谢谢支持

**Comment by yuzd** [comment]
@liwenhai0745 我查了下
--privilege是为了修改一些如/etc/sys里面的文件的时候才需要的，但正常运行一个容器，不建议开放这个权限。有可能会有安全隐患

我怀疑是你的公司环境有做特殊的权限限制。

 如果你觉得那个参数会起作用的话  建议你先自己加个这个参数来run 一个 容器

具体步骤是：

1. 先将antdeploy创建的 container 给 remove掉
2. AntDeploy已经将你的程序打包成一个image了。可以通过 docker images 查到 这个 image
 根据这个image 来run 一下你的容器，

![image](https://user-images.githubusercontent.com/16083659/62828092-51d62c80-bc10-11e9-9a83-80dce648f7f6.png)
