### ISSUE TITLE
Docker镜像发布

### ISSUE THREAD

**Issue by hao15239129517** [yuzd/AntDeploy#43]
可以添加RUN命令、环境变量这些吗？

**Comment by peiwen-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
最近在忙有事电联！

**Comment by yuzd** [comment]
镜像发布不支持，镜像发布是轻量级的，baseimage+应用=新的镜像
就这么简单
支持复杂的 得需要用容器发布它是依赖使用一台装有docker容器的宿主机来进行镜像制作的
