### ISSUE TITLE
无法编译，无法运行，dll缺少

### ISSUE THREAD

**Issue by dazhu6666** [yuzd/AntDeploy#47]
![e572dd0d7bce23835ac6a404ef1186c](https://github.com/yuzd/AntDeploy/assets/59462071/95d32903-99a5-4c3d-8750-a91b9953cc79)

![2b6ae9b6cebffee0c385c2d33e24da9](https://github.com/yuzd/AntDeploy/assets/59462071/51c8de54-e922-4688-8c76-d816b94ff770)

antdeployv2   目录下  jib.exe  缺少

master分支老旧，为何要在dev分支下面发版？

**Comment by peiwen-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
最近在忙有事电联！

**Comment by yuzd** [comment]
这个有点大，就没传到git，可以下载插件，解压后里面有
