### ISSUE TITLE
发布使用 nssm 安装为系统服务的 .net5 应用，项目发布成功后，将项目复制到了 nssm 对应的目录，导致发布后没有更新原项目的内容。

### ISSUE THREAD

**Issue by Run2948** [yuzd/AntDeploy#8]
已经测试可以成功发布项目到服务器，就是在最后更新项目文件的时候，更新到了 nssm 的安装目录。能否做出一个小小的配置，这样就可以兼容使用 nssm 等软件安装位系统服务的 .net core 应用。非常感谢！

**Comment by yuzd** [comment]
方便加我微信说下 是什么样的配置？

**Comment by Run2948** [comment]
> 方便加我微信说下 是什么样的配置？

非常乐意，更想和您交个朋友。这是我的 [微信号](https://pasteme.cn/y83uyqv1)  😄

**Comment by yuzd** [comment]
![image](https://images4.c-ctrip.com/target/0zb4r120008v0agnn1E52.png)

没看到你的微信号 你扫我吧
